# Generated by Django 5.2.7 on 2025-11-03 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='file_name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='user',
            new_name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='document',
            name='file_path',
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default='', upload_to='documents/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='court.case'),
        ),
    ]
