# Generated by Django 5.2.7 on 2025-11-03 08:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0002_rename_file_name_document_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hearing',
            old_name='date',
            new_name='date_time',
        ),
        migrations.AddField(
            model_name='hearing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hearing',
            name='judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hearing',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='court.case'),
        ),
        migrations.AlterField(
            model_name='hearing',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hearing',
            name='status',
            field=models.CharField(choices=[('zaplanowana', 'Zaplanowana'), ('odbyta', 'Odbyta'), ('odłożona', 'Odłożona')], default='zaplanowana', max_length=100),
        ),
    ]
