# Generated by Django 5.2.7 on 2025-12-02 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0002_remove_message_court_messa_room_id_0c4e45_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='assigned_judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL),
        ),
    ]
