# Generated by Django 5.2.7 on 2025-11-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0003_rename_date_hearing_date_time_hearing_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
