# Generated by Django 5.2.7 on 2025-11-03 10:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0005_alter_notification_options_notification_document_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caseparticipant',
            options={'ordering': ['joined_at']},
        ),
        migrations.AddField(
            model_name='caseparticipant',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='caseparticipant',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='caseparticipant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caseparticipant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='caseparticipant',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caseparticipant',
            name='left_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caseparticipant',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='court.case'),
        ),
        migrations.AlterField(
            model_name='caseparticipant',
            name='role_in_case',
            field=models.CharField(choices=[('plaintiff', 'Powód'), ('defendant', 'Pozwany'), ('prosecutor', 'Prokuratura'), ('accused', 'Oskarżony'), ('lawyer', 'Adwokat'), ('representative', 'Pełnomocnik'), ('witness', 'Świadek'), ('other', 'Inne')], max_length=50),
        ),
        migrations.AlterField(
            model_name='caseparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='caseparticipant',
            unique_together={('case', 'user')},
        ),
        migrations.AddIndex(
            model_name='caseparticipant',
            index=models.Index(fields=['case', 'role_in_case'], name='court_casep_case_id_0ebe4b_idx'),
        ),
        migrations.AddIndex(
            model_name='caseparticipant',
            index=models.Index(fields=['user', 'is_active'], name='court_casep_user_id_6e8cee_idx'),
        ),
    ]
