# Generated by Django 5.2.7 on 2025-12-05 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0004_case_category_case_filing_date_case_value_amount_and_more'),
        ('court', '0005_message_attachment_alter_message_content'),
    ]

    operations = [
    ]
