# Generated by Django 5.2.7 on 2025-12-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0006_merge_20251205_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Czy status online jest widoczny dla innych'),
        ),
    ]
