# Generated by Django 5.2.7 on 2025-12-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0007_user_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False, help_text='Czy użytkownik ma aktywne połączenie WebSocket'),
        ),
    ]
